---
title: "check-initial-beliefs"
author: "Manikya Alister"
format: 
  html:
   embed-resources: true
editor: visual
message: false
warning: false
code-fold: true
---

```{r}
library(tidyverse)
library(here)
```


```{r}
# load and combine empirical data 
load(here("data/experiment-3/clean/d-modelling.Rdata"))  

# filter so that we only have the baseline trials
d_baseline <- d_modelling %>%
  filter(repetitions == "rating_1") %>%
  mutate(
    initial_belief = as.numeric(scale(views)),
    baseline_belief = as.numeric(scale(confidence))
  ) %>%
  pivot_longer(cols = c("baseline_belief", "initial_belief"),
               names_to = "stage",
               values_to = "rating")

d_baseline_sum <- d_baseline %>%
  group_by(stage) %>%
  summarise(mean = mean(rating))

d_baseline %>%
  ggplot(aes(x = stage, y = rating))+
  geom_violin() 


```

```{r}
# First, reshape the data to wide format
d_wide <- d_baseline %>%
  select(participant, stage, rating) %>%
  pivot_wider(names_from = stage, values_from = rating)

# Run a paired t-test
t_test_result <- t.test(d_wide$baseline_belief, d_wide$initial_belief, paired = TRUE)

# Print the result
t_test_result
```

